version: '3.8'
services:
  db:
    image: postgres
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "127.0.0.1:5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/
